---
language: ruby
os: 'linux'
dist: 'xenial'
cache: bundler
before_install: gem install bundler --version 2.1.4
script: bundle exec rake

env:
  matrix:
    - RAILS=5.2.0 AA=2.8.1
    - RAILS=6.0.0 AA=2.8.1
    - RAILS=6.1.0 AA=2.9.0
   
rvm:
  - 2.5
  - 2.7
